---
label: default
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: 'Title '
- name: description
  type: textarea
  default: 'undefined '
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: publish_date
  type: datetime
  label: Publish Date
  description: ''
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
- name: layout
  type: text
  config:
    required: false
  label: layout
  hidden: true
  default: post
